Revert "Implement timing out in fletch_tests_suite."
This reverts commit 7e3f6fb1efbc555316566570ffe005fedcb8ab0e.

Reverting due to this stack trace:

The null object does not have a method 'kill'.

NoSuchMethodError: method not found: 'kill'
Receiver: null
Arguments: []

Review URL: https://codereview.chromium.org/1161733003