Avoid race between fletch-vm shutdown and debugger shutdown
Until now package:fletchc/fletchc.dart was (at least when using --test-debugger)
just calling 'session.shutdown()' [or before the recent refactoring,
'session.quit()'], which just closes the socket. Since the fletch-vm is still
listening for commands, it will get an EOF on the tcp connection and print:

  Failed to read from socket
  ../../src/vm/session.cc:161: error: Compiler crashed. So do we.

This stdout/stderr from the fletch-vm is captued by the fletchc debugger and
printed on it's stdout.

But after sending 'session.shutdown()' the fletchc debugger will exit() itself
very quickly.

=> So there is a race whether the error message from the fletch-vm gets picked
up by the debugger and printed out or not.

This CL should fix this race, by asking the fletch-vm to gracefully shutdown,
the debugger will then wait until it did shutdown (wait for exitcode, stdout,
stderr closing) and then will exit with the same exitcode as the fletch-vm.

R=ager@google.com

Review URL: https://codereview.chromium.org/1207863002.